### ISSUE TITLE
Could not put the node to flow editor.

### ISSUE THREAD

**Issue by belgianbeer** [CANDY-LINE/node-red-contrib-lwm2m#11]
Dear @dbaba san

I installed this software. However, I can not put the node of lwm2m to flow editing area. I was very suprised!! However, it seems fine to modify the seetings of lwm2m after importing example.

I prepared the plain Node-RED and reinstall some versions of node-red-contrib-lwm2m, 1.3, 2.0.2, etc.. It did not work.

When pick the node to editing area, there is no node at the area. but the deploy button was indicated. after that, there was the dialog when push the deploy button.
```
======================================
以下のノードは、正しくプロパティが設定されていません:
[フロー 1] lwm2m client (lwm2m client in)
[フロー 1] lwm2m client (lwm2m client out)
このままデプロイしても良いですか？
======================================
```
It in Japanese. But I believe, you can read it.

This is the system of trouble.

- OS Debian 9.9 
- Node.js  v10.16.0
- Node-RED v0.20.6
- node-red-contrib-lwm2m 2.1.2

I have another system.

- OS Debian 9.9 
- Node.js  v8.16.0
- Node-RED v0.17.5
- node-red-contrib-lwm2m 2.1.2

It woks fine. I can easy to put the node of lwm2m to editting area.

Thanks in advance.

**Comment by djDuff** [comment]
Yes, I also confirm, on v0.20.6 I can't drag lwm2m node to the area.
It was working fine on v0.20.5

**Comment by dbaba** [comment]
Thanks for the report. This is a NR issue. Will be fixed in the next release.
Read this [post](https://discourse.nodered.org/t/type-error-on-dragging-a-node-from-the-node-palette-on-nr-v0-20-6/12822/2) for detail.
