### ISSUE TITLE
bootstrap: goes to "registering" state after several hours

### ISSUE THREAD

**Issue by djDuff** [CANDY-LINE/node-red-contrib-lwm2m#13]
@dbaba san, 
I encountered one potential bug, 
I configure device to use **bootstrap**, client bootstrapping and registration is successful (in it Connected).
Then, everything is working for some hours (I don't know for how long exactly), 
then, client node is going to permanent "registering" status - it doesn't change to Registered
![image](https://user-images.githubusercontent.com/30717765/61109352-5b436c00-a48d-11e9-8358-1a48018c7f82.png)

If I re-deploy, it is working fine in most cases, 
sometimes it goes to Disconnected immediately: changing Listen port to new one helps,
Restarting Node-Red also helps.

Could you please suggest how to troubleshoot the issue?

**Comment by dbaba** [comment]
@djDuff Thanks for the report! Let me check the issue.

**Comment by dbaba** [comment]
@djDuff I've released [v2.2.0](https://github.com/CANDY-LINE/node-red-contrib-lwm2m/releases/tag/2.2.0). I ran the client a couple of nights and got no errors. Of course, it didn't fall into "registering" state during the time.
However, for the safety, I added the watchdog for the lwm2m client process, which will restart it if the process gets halted.
