### ISSUE TITLE
Integration with Arm Pelion

### ISSUE THREAD

**Issue by Nakul93** [CANDY-LINE/node-red-contrib-lwm2m#22]
Is it possible to use this node with Pelion since it uses lwm2m. Also is there a way to add the certificates to authenticate the communication

**Comment by dbaba** [comment]
I've never tried Pelion yet so I don't have any idea if it's possible.
But if Eclipse Wakaama works with Pelion, this node should work as well.
Regarding the second question, the answer is no as Wakaama doesn't support it.
