### ISSUE TITLE
Lazy-start cause an error on deployment v2.9.0

### ISSUE THREAD

**Issue by KalessWave** [CANDY-LINE/node-red-contrib-lwm2m#23]
Hi,

I encountered an issue when activating the lazy-start functionality.
The "lwm2m client node" (with the lazy start enable) raised an error at first deployment:

> TypeError: this.info is not a function

When the flow get redeploy, the node raised the following error:

> Error: Duplicate LwM2M Server Configuration (Host:leshan.eclipse.org, Port:5683, Endpoint:urn:imei:0123456789000bis)

This makes the lwm2m client unusable.
Node-red logs (even in "trace" mode, don't provide any more information)

This issue was observed on Ubuntu, with node-red 1.0.1 and 1.0.4 (latest) versions.

All over node functions with "lazy start" disable, look fine

**Comment by dbaba** [comment]
Thank you for the report.
Fix in the release 2.9.1.
