### ISSUE TITLE
Error spawn messsage - deploying LWM2M client

### ISSUE THREAD

**Issue by itpvga** [CANDY-LINE/node-red-contrib-lwm2m#25]
Hi, after installation of the lwm2m contribution for node-red and succesfull configuration of the lwm2m server credentials, the lwm2m client does not start up. This is the message I receive:

Started Node-RED graphical event wiring tool.
22 Apr 10:13:44 - [info]
Welcome to Node-RED
===================
22 Apr 10:13:44 - [info] Node-RED version: v1.0.5
22 Apr 10:13:44 - [info] Node.js  version: v11.15.0
22 Apr 10:13:44 - [info] Linux 5.0.0-1035-azure x64 LE
22 Apr 10:13:44 - [info] Loading palette nodes
22 Apr 10:13:45 - [info] Settings file  : /home/innoadmin/.node-red/settings.js
22 Apr 10:13:45 - [info] Context store  : 'default' [module=memory]
22 Apr 10:13:45 - [info] User directory : /home/innoadmin/.node-red
22 Apr 10:13:45 - [warn] Projects disabled : editorTheme.projects.enabled=false
22 Apr 10:13:45 - [info] Flows file     : /home/innoadmin/.node-red/flows_dev-vf-vm01.json
22 Apr 10:13:45 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
22 Apr 10:13:45 - [info] Starting flows
22 Apr 10:13:45 - [info] Started flows
22 Apr 10:13:45 - [info] Server now running at http://127.0.0.1:1880/
22 Apr 10:13:45 - [red] Uncaught Exception:
22 Apr 10:13:45 - Error: spawn /home/innoadmin/.node-red/node_modules/node-red-contrib-lwm2m/dist/binding/node-v67-linux-x64/wakatiwaiclient ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 2.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
22 Apr 10:13:46 - [info]
Welcome to Node-RED

**Comment by dbaba** [comment]
> 22 Apr 10:13:45 - Error: spawn /home/innoadmin/.node-red/node_modules/node-red-contrib-lwm2m/dist/binding/node-v67-linux-x64/wakatiwaiclient ENOENT

You're using Node.js v11 (=NODE_MODULE_VERSION v67).
Since the prebuilt binaries are expected to be used in Node.js v10(LTS) and v12(LTS), your Node.js environment isn't able to use the prebuilt binary. In order to get Node.js v11 compliant binary, your OS environment requires the compilation tools.

So your option is one of the following:
1. Upgrade Node.js to v12 from v11, then re-install Node-RED and additional Node-RED nodes including this node.
1. Run `sudo apt-get install build-essential` to install the compilation tools then re-install this node (uninstall then install), which will create a binary executable file for Node.js v11.

Could you please  try one of those?

**Comment by itpvga** [comment]
Thanks, I performed the updates and loaded all modules using the manage pallet.

This problem has been solved
