### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by ram1505** [CANDY-LINE/node-red-contrib-lwm2m#3]
Hi,
I'm having difficulty getting the bootstrap to work. Is it fully supported yet? The node gets stuck saying bootstrapping and no request seems to come through the LWM2M bootstrap instance.

**Comment by dbaba** [comment]
Unfortunately, the node doesn't fully support the bootstrap functionalities but partially does.

https://github.com/CANDY-LINE/node-red-contrib-lwm2m#supported-lwm2m-operations

**Comment by dbaba** [comment]
Close this issue. You can reopen it if you have new info.

**Comment by ram1505** [comment]
Hi,
This is not an issue, but how do I access the objects using POSTMAN? I'm trying to GET values of some parameters using POSTMAN.
