### ISSUE TITLE
Error: Duplicate LwM2M Server Configuration

### ISSUE THREAD

**Issue by djDuff** [CANDY-LINE/node-red-contrib-lwm2m#4]
Dear dbaba, 
I am enjoying using your plugin for node-red, thank you for develpment!

I am trying to simulate several devices and send data over LWM2M to the same server, but with different endpoints.

So i am using several "lwm2m client" nodes with different configurations:
The server URL is the same, 
but endpoints are different (each endpoint should be a separate device (with its own smart objects, etc..))
When i deploy such configuration, i get an error:
Error: Duplicate LwM2M Server Configuration (Host:<host url>, Port:5683)

is there any way to uuse the same server but with different endpoints?

Thanks in advance for your reply,
Andrey.

**Comment by dbaba** [comment]
Sorry for late response.
I understood what you'd like to do. Currently, the node doesn't allow you to create a config node having duplicate destination host and port.
Let me look into if I can modify the behavior or not.

**Comment by djDuff** [comment]
Thank you!
Yes, that's what i need - duplicate destination host and port :)
It would be great if it is possible to fix!

**Comment by dbaba** [comment]
I've published [v1.2.0](https://github.com/CANDY-LINE/node-red-contrib-lwm2m/releases/tag/1.2.0), which is available from npm as well. Please try this version.

Now you can add a server configuration having the same host and port. But duplicate client endpoint name isn't allowed for the same server host and port.

And you have to pay attention to `Listen Port` property, which is a LwM2M client listening port. The port cannot be duplicate as LwM2M server failed to communicate with the valid client.

I close this ticket but you can re-open it or issue a new one if necessary.
Thank you for your feedback.
