### ISSUE TITLE
Node responds 5.00 Internal Server Error, to Discover Operation

### ISSUE THREAD

**Issue by sblabreu** [CANDY-LINE/node-red-contrib-lwm2m#6]
Testing the Discover operation resulted in an 5.00 Internal Server Error back from LwM2M Client Node to Server.

Note the discover operation is sent at the first registration of the client to the server.
Using version 1.2.2

> No.     Time           Source                Destination           Protocol Length Info
>     501 39.708465844   192.168.42.148        104.40.191.33         CoAP     162    CON, MID:19569, POST, TKN:71 4c 84 f8, /rd?lwm2m=1.0&ep=advanbox_4&b=U&lt=300
> 
> Frame 501: 162 bytes on wire (1296 bits), 162 bytes captured (1296 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 192.168.42.148, Dst: 104.40.191.33
> User Datagram Protocol, Src Port: 56830, Dst Port: 5684
> Datagram Transport Layer Security
> Constrained Application Protocol, Confirmable, POST, MID:19569
>     01.. .... = Version: 1
>     ..00 .... = Type: Confirmable (0)
>     .... 0100 = Token Length: 4
>     Code: POST (2)
>     Message ID: 19569
>     Token: 714c84f8
>     Opt Name: #1: Uri-Path: rd
>         Opt Desc: Type 11, Critical, Unsafe
>         1011 .... = Opt Delta: 11
>         .... 0010 = Opt Length: 2
>         Uri-Path: rd
>     Opt Name: #2: Content-Format: application/link-format
>         Opt Desc: Type 12, Elective, Safe
>         0001 .... = Opt Delta: 1
>         .... 0001 = Opt Length: 1
>         Content-type: application/link-format
>     Opt Name: #3: Uri-Query: lwm2m=1.0
>         Opt Desc: Type 15, Critical, Unsafe
>         0011 .... = Opt Delta: 3
>         .... 1001 = Opt Length: 9
>         Uri-Query: lwm2m=1.0
>     Opt Name: #4: Uri-Query: ep=advanbox_4
>         Opt Desc: Type 15, Critical, Unsafe
>         0000 .... = Opt Delta: 0
>         .... 1101 = Opt Length: 13
>         Opt Length extended: 0
>         Uri-Query: ep=advanbox_4
>     Opt Name: #5: Uri-Query: b=U
>         Opt Desc: Type 15, Critical, Unsafe
>         0000 .... = Opt Delta: 0
>         .... 0011 = Opt Length: 3
>         Uri-Query: b=U
>     Opt Name: #6: Uri-Query: lt=300
>         Opt Desc: Type 15, Critical, Unsafe
>         0000 .... = Opt Delta: 0
>         .... 0110 = Opt Length: 6
>         Uri-Query: lt=300
>     End of options marker: 255
>     [Response In: 503]
>     [Uri-Path: /rd]
>     Payload: Payload Content-Format: application/link-format, Length: 39
>         Payload Desc: application/link-format
>         [Payload Length: 39]
> 
> No.     Time           Source                Destination           Protocol Length Info
>     503 39.743594320   104.40.191.33         192.168.42.148        CoAP     95     ACK, MID:19569, 2.01 Created, TKN:71 4c 84 f8, /rd
> 
> Frame 503: 95 bytes on wire (760 bits), 95 bytes captured (760 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 104.40.191.33, Dst: 192.168.42.148
> User Datagram Protocol, Src Port: 5684, Dst Port: 56830
> Datagram Transport Layer Security
> Constrained Application Protocol, Acknowledgement, 2.01 Created, MID:19569
>     01.. .... = Version: 1
>     ..10 .... = Type: Acknowledgement (2)
>     .... 0100 = Token Length: 4
>     Code: 2.01 Created (65)
>     Message ID: 19569
>     Token: 714c84f8
>     Opt Name: #1: Location-Path: rd
>         Opt Desc: Type 8, Elective, Safe
>         1000 .... = Opt Delta: 8
>         .... 0010 = Opt Length: 2
>         Location-Path: rd
>     Opt Name: #2: Location-Path: konDlzlj8H
>         Opt Desc: Type 8, Elective, Safe
>         0000 .... = Opt Delta: 0
>         .... 1010 = Opt Length: 10
>         Location-Path: konDlzlj8H
>     [Request In: 501]
>     [Response Time: 0.035128476 seconds]
>     [Uri-Path: /rd]
> 
> No.     Time           Source                Destination           Protocol Length Info
>     540 41.350836808   104.40.191.33         192.168.42.148        CoAP     89     CON, MID:31299, GET, TKN:f8 ad 46 86 05 3d 93 5d, /2
> 
> Frame 540: 89 bytes on wire (712 bits), 89 bytes captured (712 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 104.40.191.33, Dst: 192.168.42.148
> User Datagram Protocol, Src Port: 5684, Dst Port: 56830
> Datagram Transport Layer Security
> Constrained Application Protocol, Confirmable, GET, MID:31299
>     01.. .... = Version: 1
>     ..00 .... = Type: Confirmable (0)
>     .... 1000 = Token Length: 8
>     Code: GET (1)
>     Message ID: 31299
>     Token: f8ad4686053d935d
>     Opt Name: #1: Uri-Path: 2
>         Opt Desc: Type 11, Critical, Unsafe
>         1011 .... = Opt Delta: 11
>         .... 0001 = Opt Length: 1
>         Uri-Path: 2
>     Opt Name: #2: Accept: application/link-format
>         Opt Desc: Type 17, Critical, Safe
>         0110 .... = Opt Delta: 6
>         .... 0001 = Opt Length: 1
>         Accept: application/link-format
>     [Response In: 541]
>     [Uri-Path: /2]
> 
> No.     Time           Source                Destination           Protocol Length Info
>     541 41.355687283   192.168.42.148        104.40.191.33         CoAP     85     ACK, MID:31299, **5.00 Internal Server Error**, TKN:f8 ad 46 86 05 3d 93 5d, /2
> 
> Frame 541: 85 bytes on wire (680 bits), 85 bytes captured (680 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 192.168.42.148, Dst: 104.40.191.33
> User Datagram Protocol, Src Port: 56830, Dst Port: 5684
> Datagram Transport Layer Security
> Constrained Application Protocol, Acknowledgement, **5.00 Internal Server Error**, MID:31299
>     01.. .... = Version: 1
>     ..10 .... = Type: Acknowledgement (2)
>     .... 1000 = Token Length: 8
>     **Code: 5.00 Internal Server Error (160)**
>     Message ID: 31299
>     Token: f8ad4686053d935d
>     [Request In: 540]
>     [Response Time: 0.004850475 seconds]
>     [Uri-Path: /2]
> 
> No.     Time           Source                Destination           Protocol Length Info
>     542 41.382412523   104.40.191.33         192.168.42.148        CoAP     89     CON, MID:31300, GET, TKN:e8 67 47 d2 65 37 ee f5, /3
> 
> Frame 542: 89 bytes on wire (712 bits), 89 bytes captured (712 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 104.40.191.33, Dst: 192.168.42.148
> User Datagram Protocol, Src Port: 5684, Dst Port: 56830
> Datagram Transport Layer Security
> Constrained Application Protocol, Confirmable, GET, MID:31300
>     01.. .... = Version: 1
>     ..00 .... = Type: Confirmable (0)
>     .... 1000 = Token Length: 8
>     Code: GET (1)
>     Message ID: 31300
>     Token: e86747d26537eef5
>     Opt Name: #1: Uri-Path: 3
>         Opt Desc: Type 11, Critical, Unsafe
>         1011 .... = Opt Delta: 11
>         .... 0001 = Opt Length: 1
>         Uri-Path: 3
>     Opt Name: #2: Accept: application/link-format
>         Opt Desc: Type 17, Critical, Safe
>         0110 .... = Opt Delta: 6
>         .... 0001 = Opt Length: 1
>         Accept: application/link-format
>     [Response In: 543]
>     [Uri-Path: /3]
> 
> No.     Time           Source                Destination           Protocol Length Info
>     543 41.383624198   192.168.42.148        104.40.191.33         CoAP     85     ACK, MID:31300, **5.00 Internal Server Error**, TKN:e8 67 47 d2 65 37 ee f5, /3
> 
> Frame 543: 85 bytes on wire (680 bits), 85 bytes captured (680 bits) on interface 0
> Linux cooked capture
> Internet Protocol Version 4, Src: 192.168.42.148, Dst: 104.40.191.33
> User Datagram Protocol, Src Port: 56830, Dst Port: 5684
> Datagram Transport Layer Security
> Constrained Application Protocol, Acknowledgement, 5.00 Internal Server Error, MID:31300
>     01.. .... = Version: 1
>     ..10 .... = Type: Acknowledgement (2)
>     .... 1000 = Token Length: 8
>     **Code: 5.00 Internal Server Error (160)**
>     Message ID: 31300
>     Token: e86747d26537eef5
>     [Request In: 542]
>     [Response Time: 0.001211675 seconds]
>     [Uri-Path: /3]

**Comment by dbaba** [comment]
Thanks. I fixed it. I include the fix in the next release, which comes within a week.
