### ISSUE TITLE
client registers only with 0 smart object instance

### ISSUE THREAD

**Issue by djDuff** [CANDY-LINE/node-red-contrib-lwm2m#8]
Daisuke Baba san, 
 
I am trying to register on LwM2M server 
with several smart object instances.

in lwm2m client node, objects - I provide this: 

```
{
    "3303": {
        "0": {
            "5700": {
                "type": "FLOAT",
                "acl": "R",
                "value": ""
            }
        },
        "1": {
            "5700": {
                "type": "FLOAT",
                "acl": "R",
                "value": ""
            }
        }
    }
}
```

In LwM2M Server Logs I see (check **Links**: it has only **/3303/0**) :

```
Device ezhiand-nodered-dev1 registered.
Device Address: <my ip>/<my ip>
Port: 56840
Links: /, /1/0, /2/0, /3/0, /3303/0,
Binding Mode: U
Lifetime in Secs: 300
LwM2M Version: 1.0
Uses Queue Mode: false
SMS Number: null
ServerEndpointAddress: 0.0.0.0/0.0.0.0:5684
```

it will still register with only /3303/0, and not /3303/0 and /3303/1 as I expect.

Same issue happens for only one smart object, but with instance not zero
for example, in lwm2m client node, objects I provide this: 

```
{
    "3303": {
        "2": {
            "5700": {
                "type": "FLOAT",
                "acl": "R",
                "value": ""
            }
        }
    }
}
```

But client registers still with /3303/0, and not /3303/2 as I expect.

Same log in LwM2M server.

Kindly ask you to have a look at this issue, please.
Let me know if anything additional is needed.

My current config:
```
npm -v
6.4.1

node -v
v8.15.1

Node-red 
v0.20.2

node-red-contrib-lwm2m 
2.0.2
```

**Comment by dbaba** [comment]
@djDuff Thank you for the report. Another guy told me the same issue as well almost same time!
I'm now looking into this issue.
Btw, you can use the GitHub ID annotation `@dbaba` to mention me 👍, which can let me know notifications on browsing GitHub sites.

**Comment by dbaba** [comment]
Fixed. Install [v2.1.0](https://github.com/CANDY-LINE/node-red-contrib-lwm2m/releases/tag/2.1.0) and try it.

**Comment by djDuff** [comment]
@dbaba Yes, confirmed, it is working now. Thanks! :)
